QuestionsPage/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('login/', include('login.urls')),
    path('questions/', include('questions.urls')),
    path('registration/', include('registration.urls')),
    path('results/', include('results.urls')),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('', views.questions, name='questions'),
]

registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'

urlpatterns = [
    path('', views.registration, name='registration'),
]

results/urls.py
from django.urls import path
from . import views

app_name = 'results'

urlpatterns = [
    path('', views.results, name='results'),
    path('reset/', views.reset_answers, name='reset_answers'),
]

homepage/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

questions/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    CATEGORY_CHOICES = [
        ('python', 'Python'),
        ('oop', 'ООП'),
        ('data_structures', 'Структуры и типы данных'),
        ('git', 'Git'),
        ('linux', 'Linux'),
        ('docker', 'Docker'),
        ('sql', 'SQL'),
        ('network_protocols', 'Сетевые протоколы'),
        ('django', 'Django'),
    ]

    text = models.TextField()
    correct_answer = models.CharField(max_length=255)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='python')

    def __str__(self):
        return self.text


class Test(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class UserAnswer(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.CharField(max_length=1500)
    is_correct = models.BooleanField()

login/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

homepage/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    template = 'homepage/index.html'
    return render(request, template)

login/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login as auth_login, logout
from .forms import LoginForm


def user_login(request):
    template = 'login/login.html'
    error_message = None
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('questions:questions')
            else:
                error_message = "Неверное имя пользователя или пароль."
    else:
        form = LoginForm()
    return render(request, template, {'form': form, 'error_message': error_message})


def user_logout(request):
    logout(request)
    return redirect('homepage:index')

questions/views.py
from django.shortcuts import render
from .models import Question, Test, UserAnswer

def questions(request):
    template = 'questions/questions.html'
    
    # Получаем выбранные категории из GET-запроса или сессии
    if request.method == 'GET' and 'categories' in request.GET:
        categories = request.GET.getlist('categories')
        request.session['categories'] = categories
    else:
        categories = request.session.get('categories', [])

    # Получаем все вопросы, на которые пользователь уже ответил
    answered_questions = UserAnswer.objects.filter(test__user=request.user).values_list('question_id', flat=True)

    # Фильтруем вопросы, исключая уже отвеченные
    if categories:
        questions = Question.objects.filter(category__in=categories).exclude(id__in=answered_questions).order_by('id')
    else:
        questions = Question.objects.exclude(id__in=answered_questions).order_by('id')

    show_answer = request.session.get('show_answer', None)

    if request.method == 'POST':
        question_id = request.POST.get('question_id')
        question = Question.objects.get(id=question_id)

        if 'show_answer' in request.POST:
            # Показать или скрыть правильный ответ
            if show_answer == str(question_id):
                show_answer = None
            else:
                show_answer = str(question_id)
            request.session['show_answer'] = show_answer
        else:
            answer_status = request.POST.get('answer_status')

            # Удаляем предыдущие ответы на этот вопрос для текущего пользователя
            UserAnswer.objects.filter(test__user=request.user, question=question).delete()

            # Сохраняем новый ответ
            UserAnswer.objects.create(
                test=Test.objects.create(user=request.user),
                question=question,
                answer=answer_status,
                is_correct=(answer_status == 'correct')
            )

            # Обновляем список отвеченных вопросов
            answered_questions = UserAnswer.objects.filter(test__user=request.user).values_list('question_id', flat=True)

            # Получаем новый список вопросов, исключая уже отвеченные
            if categories:
                questions = Question.objects.filter(category__in=categories).exclude(id__in=answered_questions).order_by('id')
            else:
                questions = Question.objects.exclude(id__in=answered_questions).order_by('id')

    return render(request, template, {
        'questions': questions,
        'categories': categories,
        'show_answer': show_answer,
    })

results/views.py
from django.shortcuts import render, redirect
from questions.models import UserAnswer


def results(request):
    template = 'results/results.html'
    user_answers = UserAnswer.objects.filter(test__user=request.user)

    correct_answers = user_answers.filter(is_correct=True).count()
    incorrect_answers = user_answers.filter(is_correct=False, answer='incorrect').count()
    uncertain_answers = user_answers.filter(is_correct=False, answer='uncertain').count()
    total_answers = user_answers.count()

    correct_percentage = f"{correct_answers} из {total_answers}"
    incorrect_percentage = f"{incorrect_answers} из {total_answers}"
    uncertain_percentage = f"{uncertain_answers} из {total_answers}"

    incorrect_questions = user_answers.filter(answer='incorrect')
    uncertain_questions = user_answers.filter(answer='uncertain')

    return render(request, template, {
        'correct_percentage': correct_percentage,
        'incorrect_percentage': incorrect_percentage,
        'uncertain_percentage': uncertain_percentage,
        'incorrect_questions': incorrect_questions,
        'uncertain_questions': uncertain_questions
    })


def reset_answers(request):
    UserAnswer.objects.filter(test__user=request.user).delete()
    return redirect('questions:questions')

templates/base.html
<!DOCTYPE html>
<html lang="ru">
  {% include "includes/head.html" %}
  <body>
    <div class="wrapper">
      <div class="header">
        {% include "includes/header.html" %}
      </div>
      <main class="content">
        <div class="container py-5">
          {% block content %}{% endblock %}
        </div>
      </main>
      {% include "includes/footer.html" %}
    </div>
  </body>
</html>

templates/homepage/index.html
{% extends "base.html" %}
{% block title %}
  Домашняя страница
{% endblock %}
{% block content %}
<div class="home-container">
    <h1 class="home-title">Добро пожаловать на сайт QuestionsPage!</h1>
    <div class="home-content">
        <p>
            На этом сайте вы найдете вопросы, которые могут встретиться на собеседованиях python-разработчика.
        </p>
        <p>
            Для того чтобы начать работу с сайтом необходимо зарегистрироваться, перейдя на страницу "Регистрация".
            После регистрации авторизируйтесь под созданным пользователем.
        </p>
        <p>
            На главной странице Вы увидите вопрос, дайте на него ответ самостоятельно,
            после чего Вы можете посмотреть правильный ответ и соответсвующим образом оценить свой ответ.
        </p>
        <p>
            Во вкладке "Результаты" Вы можете изучить статистику своих ответов,
            а также посмотреть неуверенные и неверные ответы на вопросы.
        </p>
    </div>
</div>
{% endblock %}

templates/includes/footer.html
<footer class="footer">
  <p>© Подготовка к собеседованию</p>
</footer>

templates/includes/head.html
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel='stylesheet' href="{% static 'css/style.css' %}">
  <title>
    {% block title %}{% endblock %}
  </title>
</head>

templates/includes/header.html
{% load static %}
<div class="navbar">
    <div class="navbar-left">
        <a href="{% url 'homepage:index' %}">Домашняя страница</a>
        {% if user.is_authenticated %}
            <a href="{% url 'questions:questions' %}">Тестирование</a>
        {% endif %}
    </div>
    <div class="navbar-right">
        {% if user.is_authenticated %}
            <a href="{% url 'results:results' %}">Результаты</a>
            <a href="{% url 'login:logout' %}">Выход</a>
        {% else %}
            <a href="{% url 'login:login' %}">Логин</a>
            <a href="{% url 'registration:registration' %}">Регистрация</a>
        {% endif %}
    </div>
</div>

templates/login/login.html
{% extends "base.html" %}
{% block title %}
  Логин
{% endblock %}
{% block content %}
<div class="login-container">
    <h2 class="login-title">Вход на сайт</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Имя пользователя</label>
            {{ form.username }}
        </div>
        <div class="form-group">
            <label for="id_password">Пароль</label>
            {{ form.password }}
        </div>
        {% if error_message %}
            <div class="errors">
                <p>{{ error_message }}</p>
            </div>
        {% endif %}
        <div class="form-group">
            <label>
                <input type="checkbox" name="remember_me"> Запомнить меня
            </label>
        </div>
        <button type="submit" class="login-button">Вход</button>
    </form>
</div>
{% endblock %}

templates/questions/questions.html
{% extends "base.html" %}
{% block title %}
  Страница тестирования
{% endblock %}
{% block content %}
<div class="sidebar">
    <h3>Категории</h3>
    <form method="get" action="{% url 'questions:questions' %}">
        <div class="category">
            <label><input type="checkbox" name="categories" value="python" {% if 'python' in categories %}checked{% endif %}> Python</label>
        </div>
        <div class="category">
            <label><input type="checkbox" name="categories" value="oop" {% if 'oop' in categories %}checked{% endif %}> ООП</label>
        </div>
        <div class="category">
            <label><input type="checkbox" name="categories" value="data_structures" {% if 'data_structures' in categories %}checked{% endif %}> Структуры и типы данных</label>
        </div>
        <div class="category">
            <label><input type="checkbox" name="categories" value="git" {% if 'git' in categories %}checked{% endif %}> Git</label>
        </div>
        <div class="category">
            <label><input type="checkbox" name="categories" value="linux" {% if 'linux' in categories %}checked{% endif %}> Linux</label>
        </div>
        <div class="category">
            <label><input type="checkbox" name="categories" value="docker" {% if 'docker' in categories %}checked{% endif %}> Docker</label>
        </div>
        <div class="category">
            <label><input type="checkbox" name="categories" value="sql" {% if 'sql' in categories %}checked{% endif %}> SQL</label>
        </div>
        <div class="category">
            <label><input type="checkbox" name="categories" value="network_protocols" {% if 'network_protocols' in categories %}checked{% endif %}> Сетевые протоколы</label>
        </div>
        <div class="category">
            <label><input type="checkbox" name="categories" value="django" {% if 'django' in categories %}checked{% endif %}> Django</label>
        </div>
        <button type="submit" class="apply-button">Применить</button>
    </form>
</div>
<div class="main-content">
    {% if questions %}
        {% for question in questions %}
            <div class="question-card">
                <h2>{{ question.text }}</h2>
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="question_id" value="{{ question.id }}">
                    <button type="submit" name="show_answer" value="true" class="show-answer-button">
                        {% if show_answer == question.id|stringformat:"s" %}
                            Скрыть правильный ответ
                        {% else %}
                            Показать правильный ответ
                        {% endif %}
                    </button>
                </form>
                {% if show_answer == question.id|stringformat:"s" %}
                    <p class = "question-card-text"> Правильный ответ: {{ question.correct_answer }}</p>
                {% endif %}
                <form method="post" action="{% url 'questions:questions' %}">
                    {% csrf_token %}
                    <input type="hidden" name="question_id" value="{{ question.id }}">
                    <div class="answer-buttons">
                        <button type="submit" name="answer_status" value="correct" class="green-button">Верный ответ</button>
                        <button type="submit" name="answer_status" value="uncertain" class="yellow-button">Неуверенный ответ</button>
                        <button type="submit" name="answer_status" value="incorrect" class="red-button">Неправильный ответ</button>
                    </div>
                </form>
            </div>
        {% endfor %}
    {% else %}
        <div class="question-card">
            <h2>Вопросы из выбранной категории закончились</h2>
        </div>
    {% endif %}
</div>
{% endblock %}

templates/results/results.html
{% extends "base.html" %}
{% block title %}
  Результаты
{% endblock %}
{% block content %}
<div class="results-container">
    <h2 class="results-title">Результаты</h2>
    <div class="results-card">
        <p>Правильные ответы: {{ correct_percentage }}</p>
        <p>Неправильные ответы: {{ incorrect_percentage }}</p>
        <p>Неуверенные ответы: {{ uncertain_percentage }}</p>
    </div>

    <h3 class="results-title">Неправильные ответы</h3>
    {% for answer in incorrect_questions %}
        <div class="results-card">
            <h4>Вопрос {{ forloop.counter }}</h4>
            <p>{{ answer.question.text }}</p>
            <p>Правильный ответ: {{ answer.question.correct_answer }}</p>
        </div>
    {% endfor %}

    <h3 class="results-title">Неуверенные ответы</h3>
    {% for answer in uncertain_questions %}
        <div class="results-card">
            <h4>Вопрос {{ forloop.counter }}</h4>
            <p>{{ answer.question.text }}</p>
            <p>Правильный ответ: {{ answer.question.correct_answer }}</p>
        </div>
    {% endfor %}

    <!-- Добавляем кнопку "Начать тест заново" -->
    <form action="{% url 'results:reset_answers' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="restart-button">Начать тест заново</button>
    </form>
</div>
{% endblock %}